board/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

from board.views import (
    index,
    RedactorListView,
    TopicListView,
    NewspapersListView,
    RedactorDetailView,
    NewspaperDetailView,
    RedactorDelete,
    RedactorUpdate,
    add_comment,
    NewspaperCreateView,
    TopicCreateView,
    RedactorCreateView,
    TopicDetailView,
    NewspaperUpdateView,
    NewspaperDeleteView,
    TopicUpdateView,
    TopicDeleteView,
    newspaper_search,
)

urlpatterns = [
                  path("", index, name="index"),
                  path("redactors/", RedactorListView.as_view(), name="redactor-list"),
                  path(
                      "redactors/<int:pk>/",
                      RedactorDetailView.as_view(),
                      name="redactor-detail"),
                  path(
                      "redactor/<int:pk>/update/",
                      RedactorUpdate.as_view(),
                      name="redactor-update",
                  ),
                  path(
                      "redactor/<int:pk>/delete/",
                      RedactorDelete.as_view(),
                      name="redactor-delete"),
                  path(
                      "redactor/create/",
                      RedactorCreateView.as_view(),
                      name="redactor-create"),
                  path("newspapers/", NewspapersListView.as_view(), name="newspaper-list"),
                  path(
                      "newspaper/<int:pk>/",
                      NewspaperDetailView.as_view(),
                      name="newspaper-detail"),
                  path(
                      "newspapers/create/",
                      NewspaperCreateView.as_view(),
                      name="newspaper-create"
                  ),
                  path(
                      "newspaper/<int:pk>/update/",
                      NewspaperUpdateView.as_view(),
                      name="newspaper-update",
                  ),
                  path(
                      "newspaper/<int:pk>/delete/",
                      NewspaperDeleteView.as_view(),
                      name="newspaper-delete",
                  ),
                  path("topics/", TopicListView.as_view(), name="topic-list"),
                  path("topic/<int:pk>/", TopicDetailView.as_view(), name="topic-detail"),
                  path("topics/create/", TopicCreateView.as_view(), name="topic-create"),
                  path(
                      "manufacturers/<int:pk>/update/",
                      TopicUpdateView.as_view(),
                      name="topic-update",
                  ),
                  path(
                      "manufacturers/<int:pk>/delete/",
                      TopicDeleteView.as_view(),
                      name="topic-delete",
                  ),
                  path(
                      "newspaper/<int:newspaper_id>/add_comment/",
                      add_comment,
                      name="add-comment"
                  ),
                  path("search/", newspaper_search, name="newspaper-search"),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
app_name = "board"

newspapers_agency/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("board.urls", namespace="board")),
    path("accounts/", include("allauth.urls")),
    path("accounts/account/", include("accounts.urls")),
]

templates/includes/footer.html
<footer class="footer mt-auto py-3 bg-light">
  <div class="container text-center">
    <span class="text-muted">© 2024 Newspapers Agency. All rights reserved.</span>
  </div>
</footer>

templates/includes/pagination.html
{% if is_paginated %}
  <div class="pagination-container text-center">
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a href="?page={{ page_obj.previous_page_number }}" class="page-link">prev</a>
        </li>
      {% endif %}
      <li class="page-item active">
        <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
      </li>
      {% if page_obj.has_next %}
        <li class="page-item">
          <a href="?page={{ page_obj.next_page_number }}" class="page-link">next</a>
        </li>
      {% endif %}
    </ul>
  </div>
{% endif %}

templates/includes/search_form.html
{% block content %}
  {% load crispy_forms_filters %}
  <form method="get" action="" class="form-inline">
    {{ search_form|crispy }}
    <input class="btn btn-secondary" type="submit" value="Search">
  </form>
{% endblock %}

templates/includes/topbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
  <a class="navbar-brand" href="{% url 'board:index' %}">Newspapers Agency</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'board:redactor-list' %}"><i class="bi bi-people"></i> All Redactors</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'board:newspaper-list' %}"><i class="bi bi-newspaper"></i> All Newspapers</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'board:topic-list' %}"><i class="bi bi-tags"></i> All Topics</a>
      </li>
    </ul>

    <form class="form-inline my-2 my-lg-0 mx-auto d-flex" method="get" action="{% url 'board:newspaper-search' %}">
      <input class="form-control mr-sm-2 flex-grow-1" type="search" placeholder="Search for topics" aria-label="Search"
             name="q" title="Use '-' before name to exclude topics">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>

    <ul class="navbar-nav ml-auto">
      {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{{ user.get_absolute_url }}"><i class="bi bi-person-circle"></i> {{ user.username }}
          </a>
        </li>
        <li class="nav-item">
          <form method="post" action="{% url 'account_logout' %}" class="form-inline">
            {% csrf_token %}
            <button type="submit" class="btn btn-sm btn-outline-secondary">Logout</button>
          </form>
        </li>
      {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'account_login' %}?next={{ request.path }}"><i
              class="bi bi-box-arrow-in-right"></i> Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'account_signup' %}?next={{ request.path }}"><i
              class="bi bi-person-plus"></i> Register</a>
        </li>
      {% endif %}
    </ul>
  </div>
</nav>

templates/includes/update_delete_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} {{ object_type }}</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}