board/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

from board.views import (
    index,
    RedactorListView,
    TopicListView,
    NewspapersListView,
    RedactorDetailView,
    NewspaperDetailView,
    RedactorDelete,
    RedactorUpdate,
    add_comment,
    NewspaperCreateView,
    TopicCreateView,
    RedactorCreateView,
    TopicDetailView,
    NewspaperUpdateView,
    NewspaperDeleteView,
    TopicUpdateView,
    TopicDeleteView,
    newspaper_search,
)

urlpatterns = [
                  path("", index, name="index"),
                  path("redactors/", RedactorListView.as_view(), name="redactor-list"),
                  path(
                      "redactors/<int:pk>/",
                      RedactorDetailView.as_view(),
                      name="redactor-detail"),
                  path(
                      "redactor/<int:pk>/update/",
                      RedactorUpdate.as_view(),
                      name="redactor-update",
                  ),
                  path(
                      "redactor/<int:pk>/delete/",
                      RedactorDelete.as_view(),
                      name="redactor-delete"),
                  path(
                      "redactor/create/",
                      RedactorCreateView.as_view(),
                      name="redactor-create"),
                  path("newspapers/", NewspapersListView.as_view(), name="newspaper-list"),
                  path(
                      "newspaper/<int:pk>/",
                      NewspaperDetailView.as_view(),
                      name="newspaper-detail"),
                  path(
                      "newspapers/create/",
                      NewspaperCreateView.as_view(),
                      name="newspaper-create"
                  ),
                  path(
                      "newspaper/<int:pk>/update/",
                      NewspaperUpdateView.as_view(),
                      name="newspaper-update",
                  ),
                  path(
                      "newspaper/<int:pk>/delete/",
                      NewspaperDeleteView.as_view(),
                      name="newspaper-delete",
                  ),
                  path("topics/", TopicListView.as_view(), name="topic-list"),
                  path("topic/<int:pk>/", TopicDetailView.as_view(), name="topic-detail"),
                  path("topics/create/", TopicCreateView.as_view(), name="topic-create"),
                  path(
                      "manufacturers/<int:pk>/update/",
                      TopicUpdateView.as_view(),
                      name="topic-update",
                  ),
                  path(
                      "manufacturers/<int:pk>/delete/",
                      TopicDeleteView.as_view(),
                      name="topic-delete",
                  ),
                  path(
                      "newspaper/<int:newspaper_id>/add_comment/",
                      add_comment,
                      name="add-comment"
                  ),
                  path("search/", newspaper_search, name="newspaper-search"),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
app_name = "board"

newspapers_agency/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("board.urls", namespace="board")),
    path("accounts/", include("allauth.urls")),
    path("accounts/account/", include("accounts.urls")),
]

board/models.py
from django.conf import settings
from django.db import models
from django_ckeditor_5.fields import CKEditor5Field


class Topic(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name


class Newspaper(models.Model):
    title = models.CharField(max_length=100)
    content = CKEditor5Field('content', config_name='extends')
    publisher_date = models.DateField(auto_now_add=True)
    topic = models.ManyToManyField(Topic, related_name="newspapers")
    redactor = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="newspapers"
    )
    image = models.ImageField(upload_to="newspapers", blank=True, null=True)

    def __str__(self):
        return f"{self.title} {self.publisher_date}"


class Comment(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    newspaper = models.ForeignKey(
        Newspaper, on_delete=models.CASCADE, related_name="comments"
    )
    redactor = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="comments"
    )

    def __str__(self):
        return f"Comment by {self.redactor.username} on {self.newspaper.title}"

board/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django_ckeditor_5.widgets import CKEditor5Widget

from accounts.models import Redactor
from board.models import Newspaper, Topic


class RedactorCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Redactor
        fields = UserCreationForm.Meta.fields + (
            "years_of_experience",
            "email",
            "first_name",
            "last_name",
            "profile_image"
        )


class RedactorUpdateForm(forms.ModelForm):
    class Meta:
        model = Redactor
        fields = (
            "first_name",
            "last_name",
            "email",
            "username",
            "years_of_experience",
            "profile_image",
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["profile_image"].widget.attrs["class"] = "form-control-file"


class NewspaperForm(forms.ModelForm):
    redactor = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["content"].required = False
    class Meta:
        model = Newspaper
        fields = ["title", "content", "topic", "redactor", "image"]
        widgets = {
            "content": CKEditor5Widget(
                attrs={"class": "django_ckeditor_5"}, config_name="default"
            )
        }


class NewspaperSearchForm(forms.Form):
    title = forms.CharField(
        max_length=100,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by title"}),
    )


class RedactorSearchForm(forms.Form):
    username = forms.CharField(
        max_length=100,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by username"}),
    )


class TopicSearchForm(forms.Form):
    name = forms.CharField(
        max_length=100,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by name"}),
    )


class TopicCreateForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ["name"]

board/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Q
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic

from board.forms import (
    RedactorUpdateForm,
    NewspaperForm,
    RedactorSearchForm,
    TopicSearchForm,
    NewspaperSearchForm,
    TopicCreateForm,
    RedactorCreationForm,
)
from board.models import Topic, Newspaper, Comment
from accounts.models import Redactor


@login_required
def index(request):
    num_newspapers = Newspaper.objects.count()
    num_redactors = Redactor.objects.count()
    num_topics = Topic.objects.count()
    topics = Topic.objects.all()
    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1

    context = {
        "num_newspapers": num_newspapers,
        "num_redactors": num_redactors,
        "num_topics": num_topics,
        "num_visits": num_visits,
        "topics": topics,
    }

    return render(request, "board/index.html", context)


class RedactorListView(LoginRequiredMixin, generic.ListView):
    model = Redactor
    template_name = "board/redactor_list.html"
    context_object_name = "redactors"
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(RedactorListView, self).get_context_data(**kwargs)
        context["search_form"] = RedactorSearchForm()
        return context

    def get_queryset(self):
        queryset = Redactor.objects.all()
        form = RedactorSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(
                username__icontains=form.cleaned_data["username"]
            )
        return queryset


class RedactorDetailView(LoginRequiredMixin, generic.DetailView):
    template_name = "board/redactor_detail.html"
    model = Redactor
    queryset = Redactor.objects.prefetch_related("newspapers__topic")
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        redactor = self.get_object()
        newspapers = redactor.newspapers.all()
        paginator = Paginator(newspapers, self.paginate_by)
        page = self.request.GET.get("page")
        try:
            newspapers = paginator.page(page)
        except PageNotAnInteger:
            newspapers = paginator.page(1)
        except EmptyPage:
            newspapers = paginator.page(paginator.num_pages)
        context["newspapers"] = newspapers
        return context


class RedactorCreateView(LoginRequiredMixin, generic.CreateView):
    model = Redactor
    form_class = RedactorCreationForm
    template_name = "board/redactor_form.html"


class RedactorUpdate(LoginRequiredMixin, generic.UpdateView):
    model = Redactor
    form_class = RedactorUpdateForm
    success_url = reverse_lazy("board:redactor-list")
    template_name = "board/redactor_update.html"

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(pk=self.request.user.pk)


class RedactorDelete(LoginRequiredMixin, generic.DeleteView):
    model = Redactor
    success_url = reverse_lazy("board:redactor-list")
    template_name = "board/redactor_confirm_delete.html"


class TopicListView(LoginRequiredMixin, generic.ListView):
    model = Topic
    template_name = "board/topic_list.html"
    context_object_name = "topics"
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TopicListView, self).get_context_data(**kwargs)
        context["search_form"] = TopicSearchForm()
        return context

    def get_queryset(self):
        queryset = Topic.objects.all()
        name = self.request.GET.get("name")
        if name:
            return queryset.filter(name__icontains=name)
        return queryset


class TopicDetailView(generic.DetailView):
    model = Topic
    template_name = "board/topic_detail.html"
    context_object_name = "topic"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["newspapers"] = self.object.newspapers.all()
        return context


class TopicCreateView(LoginRequiredMixin, generic.CreateView):
    model = Topic
    form_class = TopicCreateForm
    template_name = "board/topic_form.html"
    success_url = reverse_lazy("board:topic-list")


class TopicUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Topic
    fields = "__all__"
    success_url = reverse_lazy("board:topic-list")


class TopicDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Topic
    success_url = reverse_lazy("board:topic-list")


class NewspapersListView(LoginRequiredMixin, generic.ListView):
    model = Newspaper
    template_name = "board/newspaper_list.html"
    context_object_name = "newspapers"
    paginate_by = 6

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(NewspapersListView, self).get_context_data(**kwargs)
        context["search_form"] = NewspaperSearchForm()
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        model = self.request.GET.get("model")
        if model:
            queryset = queryset.filter(model__icontains=model)
        return queryset


class NewspaperCreateView(LoginRequiredMixin, generic.CreateView):
    model = Newspaper
    form_class = NewspaperForm
    template_name = "board/newspaper_form.html"
    success_url = reverse_lazy("board:newspaper-list")


class NewspaperDetailView(LoginRequiredMixin, generic.DetailView):
    model = Newspaper
    context_object_name = "newspaper"


class NewspaperUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Newspaper
    form_class = NewspaperForm
    success_url = reverse_lazy("board:newspaper-list")


class NewspaperDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Newspaper
    success_url = reverse_lazy("board:newspaper-list")


@login_required
def add_comment(request, newspaper_id):
    if request.method == "POST":
        newspaper = Newspaper.objects.get(id=newspaper_id)
        content = request.POST.get("content")
        redactor = request.user
        Comment.objects.create(
            newspaper=newspaper,
            content=content,
            redactor=redactor
        )
        return redirect("board:newspaper-detail", pk=newspaper_id)

    return redirect("board:index")


@login_required
def newspaper_search(request):
    query = request.GET.get("q", "")
    if query:
        terms = query.split(",")
        include_topics = []
        exclude_topics = []
        include_redactors = []

        for term in terms:
            term = term.strip()
            if term.startswith("-"):
                if " " in term:
                    exclude_topics.append(term[1:])
            else:
                if " " in term:
                    include_redactors.append(term)
                else:
                    include_topics.append(term)

        include_topic_queries = Q()
        for topic in include_topics:
            include_topic_queries |= Q(topic__name__icontains=topic)

        exclude_topic_queries = Q()
        for topic in exclude_topics:
            exclude_topic_queries |= Q(topic__name__icontains=topic)

        newspapers = (
            Newspaper.objects.filter(
                include_topic_queries,
            )
            .exclude(exclude_topic_queries)
            .distinct()
        )
    else:
        newspapers = Newspaper.objects.none()

    return render(
        request,
        "board/newspaper_search.html",
        {"newspapers": newspapers, "query": query},
    )

templates/board/index.html
{% extends "base.html" %}

{% block content %}
  <div class="container mt-5">
    <div class="row">
      <div class="col-md-12 text-center">
        <h1 class="display-4">Newspapers Agency</h1>
        <h2 class="my-4">Show the news of the whole world</h2>
        <p class="lead">The Newspapers Agency has:</p>
        <div class="row mb-4">
          <div class="col-md-4">
            <div class="list-group">
              <div class="list-group-item">
                <strong>Newspapers:</strong> {{ num_newspapers }}
              </div>
            </div>
          </div>
          <div class="col-md-4">
            <div class="list-group">
              <div class="list-group-item">
                <strong>Redactors:</strong> {{ num_redactors }}
              </div>
            </div>
          </div>
          <div class="col-md-4">
            <div class="list-group">
              <div class="list-group-item">
                <strong>Topics:</strong> {{ num_topics }}
              </div>
            </div>
          </div>
        </div>
        <p class="lead">
          You have visited this page
          {{ num_visits }} time{{ num_visits|pluralize }}.
        </p>
        <hr>
        {% for topic in topics %}
          <div class="mt-4">
            <h3>{{ topic.name }}</h3>
            <div class="row">
              {% for newspaper in topic.newspapers.all|slice:"0:4" %}
                <div class="col-md-3 mb-4">
                  <a href="{% url 'board:newspaper-detail' pk=newspaper.id %}" class="text-decoration-none text-dark">
                    <div class="card h-100"
                         style="{% if newspaper.image %}background-image: url({{ newspaper.image.url }});{% else %}background-color: #f8f9fa;{% endif %} background-size: cover; background-position: center;">
                      <div class="card-body d-flex align-items-end" style="background: rgba(0, 0, 0, 0.5);">
                        <h5 class="card-title text-white">{{ newspaper.title }}</h5>
                      </div>
                    </div>
                  </a>
                </div>
              {% endfor %}
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
  </div>
{% endblock %}

templates/board/newspaper_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete newspaper?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/board/newspaper_detail.html
{% extends "base.html" %}

{% block content %}
  <div class="container mt-5">
    <div class="row">
      <div class="col-md-8 offset-md-2">
        <div class="card mb-3">
          <div class="card-body">
            {% if newspaper.image %}
              <div class="mb-3"
                   style="background-image: url('{{ newspaper.image.url }}'); background-size: cover; background-position: center; height: 300px; position: relative;">
                <div
                    style="background: rgba(0, 0, 0, 0.5); color: white; height: 100%; display: flex; align-items: center; justify-content: center;">
                  <h1 class="card-title">{{ newspaper.title }}</h1>
                </div>
              </div>
            {% else %}
              <h1 class="card-title">{{ newspaper.title }}</h1>
            {% endif %}
            <div class="mb-3">
              <h5>Topics:</h5>
              <div class="d-flex flex-wrap">
                {% for topic in newspaper.topic.all %}
                  <span class="badge badge-info mr-2 mb-2">
                    <a class="standard-link" style="color: #343a40; background: antiquewhite"
                       href="{% url 'board:topic-detail' pk=topic.id %}">{{ topic.name }}</a>
                  </span>
                {% endfor %}
              </div>
            </div>
            <div class="mb-3">
              <h5>Redactors:</h5>
              <div class="d-flex flex-wrap">
                {% for redactor in newspaper.redactor.all %}
                  <span class="badge badge-secondary mr-2 mb-2">
                    <a class="standard-link" style="color: #343a40; background: antiquewhite"
                       href="{% url 'board:redactor-detail' pk=redactor.id %}">{{ redactor.username }}</a>
                  </span>
                {% endfor %}
              </div>
            </div>
            <div class="mb-3">
              <p class="card-text">{{ newspaper.content }}</p>
            </div>
            {% if user.is_staff %}
              <div class="mt-4">
                <a href="{% url 'board:newspaper-delete' newspaper.pk %}" class="btn btn-danger">Delete newspaper</a>
                <a href="{% url 'board:newspaper-update' newspaper.pk %}" class="btn btn-primary">Update newspaper</a>
              </div>
            {% endif %}
          </div>
        </div>

        <div class="card mt-3">
          <div class="card-body">
            <h3 class="card-title">Comments</h3>
            <ul class="list-group mb-3">
              {% for comment in newspaper.comments.all %}
                <li class="list-group-item">
                  <div class="d-flex justify-content-between align-items-center">
                    <div>
                      <strong>{{ comment.redactor.username }}</strong> - {{ comment.created_at|date:"F d, Y H:i" }}
                    </div>
                    <div class="text-muted">{{ comment.created_at|timesince }} ago</div>
                  </div>
                  <p>{{ comment.content }}</p>
                </li>
              {% empty %}
                <li class="list-group-item">No comments yet.</li>
              {% endfor %}
            </ul>
            <hr>
            <h3>Add a Comment</h3>
            <form method="post" action="{% url 'board:add-comment' newspaper.id %}">
              {% csrf_token %}
              <div class="form-group">
                <label for="comment_content">Your Comment</label>
                <textarea class="form-control" id="comment_content" name="content" rows="3" required></textarea>
              </div>
              <br>
              <button type="submit" class="btn btn-primary">Submit</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/board/newspaper_list.html
{% extends "base.html" %}

{% block content %}
  <div class="container">
    <div class="d-flex justify-content-between align-items-center mb-4">
      <h1 class="mt-5 mb-4">Newspapers</h1>
      {% if user.is_staff %}
        <a href="{% url 'board:newspaper-create' %}" class="btn btn-primary">Create Newspaper</a>
      {% endif %}

    </div>

    {% if newspapers %}
      {% include "includes/search_form.html" %}
      <br>
      <div class="row">
        {% for newspaper in newspapers %}
          <div class="col-md-6 mb-3">
            <div class="card">
              <div class="card-body">
                <h5 class="card-title">
                  <a href="{% url 'board:newspaper-detail' pk=newspaper.id %}">{{ newspaper.title }}</a>
                </h5>
                {% if newspaper.topic.all %}
                  <p class="card-text"><small class="text-muted">Topic: {{ newspaper.topic.all|join:", " }}</small></p>
                {% endif %}
                <p class="card-text"><small class="text-muted">Redactor: {{ newspaper.redactor.all|join:", " }}</small>
                </p>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    {% else %}
      <div class="alert alert-info" role="alert">
        There are no newspapers on board.
      </div>
    {% endif %}
  </div>
{% endblock %}

templates/board/redactor_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <div class="container mt-5">
    <div class="card">
      <div class="card-header">
        <h1>Confirm Deletion</h1>
      </div>
      <div class="card-body">
        <p>Are you sure you want to delete your account, <strong>{{ redactor.username }}</strong>?</p>
        <form method="post">{% csrf_token %}
          <button type="submit" class="btn btn-danger">Yes, delete my account</button>
          <a href="{% url 'board:redactor-detail' redactor.pk %}" class="btn btn-secondary">No, take me back</a>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

templates/board/redactor_detail.html
{% extends "base.html" %}

{% block content %}
  <div class="container mt-5">
    <div class="card">
      <div class="card-header">
        <h1>Username: {{ redactor.username }}</h1>
      </div>
      <div class="card-body">
        <div class="row">
          <div class="col-md-3">
            {% if redactor.profile_image %}
              <img src="{{ redactor.profile_image.url }}" alt="Profile Image" class="img-fluid mb-3">
            {% else %}
              <div>Empty image</div>
            {% endif %}
          </div>
          <div class="col-md-9">
            <p><strong>First name:</strong> {{ redactor.first_name }}</p>
            <p><strong>Last name:</strong> {{ redactor.last_name }}</p>
            <p><strong>Email:</strong> {{ redactor.email }}</p>
            <p><strong>Years of experience:</strong> {{ redactor.years_of_experience }}</p>
            <p><strong>Is staff:</strong> <span style="color: black; background: #28a745"
                                                class="badge  {{ redactor.is_staff|yesno:'badge-success,badge-secondary' }}">{{ redactor.is_staff|yesno:'Yes,No' }}</span>
            </p>
          </div>
        </div>
        {% if user == redactor %}
          <div class="mt-4">
            <a href="{% url 'board:redactor-delete' redactor.pk %}" class="btn btn-danger">Delete My Account</a>
            <a href="{% url 'board:redactor-update' redactor.pk %}" class="btn btn-primary">Update My Account</a>
          </div>
        {% endif %}
        <div class="mt-4">
          <h4>Newspapers</h4>
          {% if newspapers %}
            {% for newspaper in newspapers %}
              <div class="card mb-3">
                <div class="card-body">
                  <p><strong>Title:</strong> <a
                      href="{% url 'board:newspaper-detail' newspaper.pk %}">{{ newspaper.title }}</a></p>
                  <p><strong>Content:</strong> {{ newspaper.content|truncatechars:100 }}</p>
                  <p><strong>Topics:</strong>
                    {% for topic in newspaper.topic.all %}
                      {{ topic.name }}{% if not forloop.last %}, {% endif %}
                    {% endfor %}
                  </p>
                </div>
              </div>
            {% endfor %}
            <nav aria-label="Page navigation">
              <ul class="pagination justify-content-center">
                {% if newspapers.has_previous %}
                  <li class="page-item">
                    <a class="page-link" href="?page=1" aria-label="First">
                      <span aria-hidden="true">&laquo;</span>
                    </a>
                  </li>
                  <li class="page-item">
                    <a class="page-link" href="?page={{ newspapers.previous_page_number }}" aria-label="Previous">
                      <span aria-hidden="true">&lsaquo;</span>
                    </a>
                  </li>
                {% endif %}
                <li class="page-item disabled">
                  <span class="page-link">Page {{ newspapers.number }} of {{ newspapers.paginator.num_pages }}</span>
                </li>
                {% if newspapers.has_next %}
                  <li class="page-item">
                    <a class="page-link" href="?page={{ newspapers.next_page_number }}" aria-label="Next">
                      <span aria-hidden="true">&rsaquo;</span>
                    </a>
                  </li>
                  <li class="page-item">
                    <a class="page-link" href="?page={{ newspapers.paginator.num_pages }}" aria-label="Last">
                      <span aria-hidden="true">&raquo;</span>
                    </a>
                  </li>
                {% endif %}
              </ul>
            </nav>
          {% else %}
            <p class="alert alert-warning">No newspapers!</p>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/board/redactor_list.html
{% extends "base.html" %}

{% block content %}
  <div class="container">
    <div class="d-flex justify-content-between align-items-center mb-4">
      <h1 class="mt-5 mb-4">Redactors</h1>
      {% if user.is_staff %}
        <a href="{% url 'board:redactor-create' %}" class="btn btn-primary">Create Redactor</a>
      {% endif %}
    </div>

    {% if redactors %}
      {% include "includes/search_form.html" %}
      <br>
      <div class="list-group">
        {% for redactor in redactors %}
          <div class="list-group-item list-group-item-action d-flex align-items-center mb-3">
            <div class="me-3">
              {% if redactor.profile_image %}
                <img src="{{ redactor.profile_image.url }}" alt="Profile Image" class="img-fluid rounded-circle"
                     style="width: 100px; height: 100px; object-fit: cover;">
              {% else %}
                <div class="rounded-circle bg-secondary d-flex justify-content-center align-items-center"
                     style="width: 100px; height: 100px; object-fit: cover;">
                  <span class="text-white">No Image</span>
                </div>
              {% endif %}
            </div>
            <div>
              <h5 class="mb-1">
                <a href="{{ redactor.get_absolute_url }}">
                  {{ redactor.username }} {% if user == redactor %} (Me){% endif %}
                </a>
              </h5>
              <p class="mb-1">{{ redactor.first_name }} {{ redactor.last_name }}</p>
              <p class="mb-0">Years of Experience: {{ redactor.years_of_experience }}</p>
            </div>
          </div>
        {% endfor %}
      </div>
    {% else %}
      <p class="mt-3">There are no redactors in the service.</p>
    {% endif %}
  </div>
{% endblock %}

templates/board/redactor_update.html
{% extends "base.html" %}

{% block content %}
  <div class="container mt-5">
    <div class="card">
      <div class="card-header">
        <h1>Update Account: {{ form.instance.username }}</h1>
      </div>
      <div class="card-body">
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {{ form.as_p }}
          <button type="submit" class="btn btn-primary">Save changes</button>
          <a href="{% url 'board:redactor-detail' form.instance.pk %}" class="btn btn-secondary">Cancel</a>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

templates/board/topic_list.html
{% extends "base.html" %}

{% block content %}
  <div class="container">
    <div class="d-flex justify-content-between align-items-center mb-4">
      <h1 class="mt-5 mb-4">Topics</h1>
      {% if user.is_staff %}
        <a href="{% url 'board:topic-create' %}" class="btn btn-primary">Create topic</a>
      {% endif %}
    </div>
    {% if topics %}
      {% include "includes/search_form.html" %}
      <br>
      <div class="table-responsive">
        <table class="table table-striped">
          <thead>
          <tr>
            <th>ID</th>
            <th>Name</th>
            {% if user.is_staff %}
              <th>Update</th>
              <th>Delete</th>
            {% endif %}
          </tr>
          </thead>
          <tbody>
          {% for topic in topics %}
            <tr>
              <td>{{ topic.id }}</td>
              <td>
                <a href="{% url 'board:topic-detail' topic.id %}">{{ topic.name }}</a>
              </td>
              {% if user.is_staff %}
                <td>
                  <a href="{% url 'board:topic-update' pk=topic.id %}" class="btn btn-sm btn-primary">Update</a>
                </td>
                <td>
                  <form action="{% url 'board:topic-delete' pk=topic.id %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-sm btn-danger"
                            onclick="return confirm('Are you sure you want to delete this topic?')">Delete
                    </button>
                  </form>
                </td>
              {% endif %}
            </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>
    {% else %}
      <p class="mt-3">There are no topics in the board.</p>
    {% endif %}
  </div>
{% endblock %}